---
    - name: install basic packages
      sudo: yes
      yum: name={{ item }} state=present
      with_items:
          - curl
          - git
          - gcc 
          - gcc-c++ 
          - automake 
          - autoconf 
          - make
          - c-ares
          - c-ares-devel

    - name: download nodejs rpm
      sudo: yes
      get_url: url=http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz dest=/usr/src/node-v0.10.26.tar.gz

    - name: extract nodejs
      sudo: yes
      command: chdir=/usr/src/ tar xvf node-v0.10.26.tar.gz

    - name: configure nodejs
      sudo: yes
      command: chdir=/usr/src/node-v0.10.26/ ./configure

    - name: make nodejs
      sudo: yes
      command: chdir=/usr/src/node-v0.10.26/ make

    - name: install nodejs
      sudo: yes
      command: chdir=/usr/src/node-v0.10.26/ make install
